### ISSUE TITLE
Using `\jobname` in `templates/article/template.tex` is dangerous

### ISSUE THREAD

**Issue by ragonneau** [equipez/textools#1]
Hi @zaikunzhang,

I think it is dangerous to use `\jobname` in `templates/article/template.tex` for the following reason.

I did it initially in PDFO's paper, and the compilation on arXiv did not work because the value of `\jobname` there is not the file's name without an extension but another one. I suggest hardcoding the name of the Bib file.

Also, I believe it may be helpful to add `equipez/bibliography` as a submodule of the current repo, as the file `ref.bib` would then be available here.

Regards,
Tom.

**Comment by zaikunzhang** [comment]
Thanks, Tom. 

We do not need to and should not apply the template to papers that have been finished. 

The template is meant to be used when a paper starts. Inevitably, adjustments will be made to the paper being written during the writing (e.g., changing \jobname to another string, if needed). Some of the adjustments should be upstreamed to the template if they are improvements, but some of them will be specific to the paper. 

> Also, I believe it may be helpful to add equipez/bibliography as a submodule of the current repo, as the file ref.bib would then be available here.

Please do it. I suppose you have access to both repos. 

Thanks.

**Comment by ragonneau** [comment]
Dear Zaikun,

I do not mean I applied this template to PDFO's paper; I meant that I had the same idea when we wrote the paper.

Regards,
Tom.

**Comment by zaikunzhang** [comment]
Understood. Good to know it. Thank you.
